# Generated by Django 4.2.5 on 2023-10-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='clubs',
            field=models.ManyToManyField(to='users.clubs'),
        ),
        migrations.AlterField(
            model_name='students',
            name='units',
            field=models.ManyToManyField(to='users.units'),
        ),
    ]
