# Generated by Django 4.2.5 on 2023-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_java_prediction_javascript_prediction_php_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
