# Generated by Django 4.2.5 on 2023-10-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
