# Generated by Django 4.2.5 on 2023-10-11 09:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_students_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
        migrations.AddField(
            model_name='students',
            name='phone_no',
            field=models.CharField(default='1234567890', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number'),
        ),
    ]
