# Generated by Django 4.2.5 on 2023-10-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_students_phone_students_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default='NULL', max_length=254),
        ),
    ]
