# Generated by Django 4.2.5 on 2023-10-30 11:50

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_students_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_no',
            field=models.CharField(default='07xxx', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message=None), django.core.validators.MinLengthValidator(10)], verbose_name='Phone number'),
        ),
    ]
