# Generated by Django 4.2.5 on 2023-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_sqlattendance_pythonattendance_phpattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsattendance',
            name='From_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='jsattendance',
            name='To_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='jsattendance',
            name='reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phpattendance',
            name='From_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='phpattendance',
            name='To_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='phpattendance',
            name='reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pythonattendance',
            name='From_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='pythonattendance',
            name='To_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='pythonattendance',
            name='reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sqlattendance',
            name='From_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='sqlattendance',
            name='To_hrs',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
        migrations.AddField(
            model_name='sqlattendance',
            name='reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jsattendance',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='phpattendance',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pythonattendance',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='sqlattendance',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
