# Generated by Django 4.2.5 on 2023-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_jsattendance_from_hrs_jsattendance_to_hrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsattendance',
            name='present',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=50),
        ),
        migrations.AddField(
            model_name='phpattendance',
            name='present',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=50),
        ),
        migrations.AddField(
            model_name='pythonattendance',
            name='present',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=50),
        ),
        migrations.AddField(
            model_name='sqlattendance',
            name='present',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=50),
        ),
    ]
