# Generated by Django 4.2.5 on 2023-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_days_java_hours_rename_days_javascript_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonattendance',
            name='sumhrs',
            field=models.IntegerField(default=0),
        ),
    ]
