# Generated by Django 4.2.5 on 2023-11-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_pythonattendance_sumhrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsattendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsattendance',
            name='sumhrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phpattendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phpattendance',
            name='sumhrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pythonattendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqlattendance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sqlattendance',
            name='sumhrs',
            field=models.IntegerField(default=0),
        ),
    ]
